### ISSUE TITLE
symfony 3.0

### ISSUE THREAD

**Issue by whyte624** [hilobok/AnhSapeBundle#3]
Please, put your service in quotes here: vendor/anh/sape-bundle/Resources/config/services.yml
like that 

```
services:
    anh_sape.twig.sape_extension:
        class: Anh\SapeBundle\Twig\SapeExtension
        arguments:
            - '@anh_sape.sape_client'
        tags:
            - { name: twig.extension }

```
